[package]
name = "brdgme-markup"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-color = { git = "https://github.com/brdgme/color.git" }
serde = "0.9.13"
serde_derive = "0.9.13"
combine = "2.3.1"
