[package]
name = "brdgme-markup"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { path = "../std" }
brdgme-color = { path = "../color" }
serde = "*"
serde_derive = "*"
combine = "*"
